name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        type: string

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create and push tag
        env:
          TAG_NAME: ${{ github.event.inputs.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Creating tag: ${{ github.event.inputs.tag_name }}"
          echo "NEXT_VERSION=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          tag="${{ github.event.inputs.tag_name }}"
          message="Release ${{ github.event.inputs.tag_name }}"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"

      - name: Get the new tag
        id: get_new_tag
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          echo "Extracted Tag Name: $TAG_NAME"